spring.config.import=optional:file:.env[.properties]
spring.application.name=RunTrack

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

strava.client-id=${STRAVA_CLIENT_ID}
strava.client-secret=${STRAVA_CLIENT_SECRET}
strava.redirect-uri=${STRAVA_REDIRECT_URI}

app.frontend-url=${FRONTEND_URL}

gemini.api-key=${GEMINI_API_KEY}
gemini.model=gemini-3.6-flash

logging.level.org.springframework.security=${SECURITY_LOG_LEVEL:INFO}